src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{
    
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id; //automatically put, the primary key

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title; //will always automatically create the getters and setters

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    
    public function __construct() {
        $this->created_at = new \DateTime();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    
    public function getSlug():string {
        return (new Slugify())->slugify($this->title);
    }
    
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
    
    public function getFormattedPrice(): string 
    {
        return number_format($this->price, 0, '', ' '); //o is # after decimal, '' is no space after decimal point, ' ' is space between thousands and hundreds
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    
    public function getHeatType(): string
    {
      return self::HEAT[$this->heat];  //written like this because we want to recoup the array
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    
}

templates/pages/home.html.twig
{% extends "base.html.twig" %}

{% block title 'Mon Agence' %}

{% block body %}
    
    <div class="jumbotron text-center">
        <h1>Agence</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis
            nunc a vehicula bibendum. Integer vestibulum laoreet consectetur.
            Nam porta lacus vitae massa vehicula condimentum. </p>
    </div>
    
    <div class="container">
        <h2>Les derniers biens</h2>
        <div class="row flex">
            {% for property in properties %}
                <div class="col-3">
                    <div class="card">
                        <div class="card-boby">
                            <h5 class="card-title">
                                <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
                            </h5>
                            <p class="card-text">{{ property.city }} ({{ property.postalCode }})</p>
                            <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{ property.getFormattedPrice }} €</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}